server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index login.html index.html;

    location = / {
        return 301 /login;
    }

    location / {
        try_files $uri $uri/ $uri.html /login.html =404;
    }
}
